<h1 class="judulhalaman">Our Blogs</h1>
        <p class="newsdetail">
        <img src="images/Penguins.jpg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis odio. Duis at laoreet ipsum. In vitae lacinia massa. Phasellus rutrum, erat ac tempor malesuada, enim tortor malesuada velit, eu euismod augue eros ut nisi. Vivamus interdum bibendum congue. Integer semper pulvinar lectus, at vehicula ante scelerisque sed. Cras tristique felis sit amet orci ultrices mattis. Nulla quis eleifend sem, vitae rutrum nunc. Praesent quis molestie mi. Donec suscipit suscipit nisi ac suscipit. Suspendisse ante magna, accumsan a placerat non, accumsan vitae eros. Proin in turpis nec nisi imperdiet feugiat. Ut sagittis fermentum dolor, at volutpat orci tincidunt sed. Sed consectetur pharetra arcu ut sodales. Proin eleifend diam eget ante blandit, at semper urna euismod. Vivamus rhoncus arcu in massa condimentum, cursus congue eros ultricies. </p>
        
        <p class="newsdetail">
        <img src="images/Lighthouse.jpg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis odio. Duis at laoreet ipsum. In vitae lacinia massa. Phasellus rutrum, erat ac tempor malesuada, enim tortor malesuada velit, eu euismod augue eros ut nisi. Vivamus interdum bibendum congue. Integer semper pulvinar lectus, at vehicula ante scelerisque sed. Cras tristique felis sit amet orci ultrices mattis. Nulla quis eleifend sem, vitae rutrum nunc. Praesent quis molestie mi. Donec suscipit suscipit nisi ac suscipit. Suspendisse ante magna, accumsan a placerat non, accumsan vitae eros. Proin in turpis nec nisi imperdiet feugiat. Ut sagittis fermentum dolor, at volutpat orci tincidunt sed. Sed consectetur pharetra arcu ut sodales. Proin eleifend diam eget ante blandit, at semper urna euismod. Vivamus rhoncus arcu in massa condimentum, cursus congue eros ultricies. </p>
        
        <p class="newsdetail">
        <img src="images/Koala.jpg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis odio. Duis at laoreet ipsum. In vitae lacinia massa. Phasellus rutrum, erat ac tempor malesuada, enim tortor malesuada velit, eu euismod augue eros ut nisi. Vivamus interdum bibendum congue. Integer semper pulvinar lectus, at vehicula ante scelerisque sed. Cras tristique felis sit amet orci ultrices mattis. Nulla quis eleifend sem, vitae rutrum nunc. Praesent quis molestie mi. Donec suscipit suscipit nisi ac suscipit. Suspendisse ante magna, accumsan a placerat non, accumsan vitae eros. Proin in turpis nec nisi imperdiet feugiat. Ut sagittis fermentum dolor, at volutpat orci tincidunt sed. Sed consectetur pharetra arcu ut sodales. Proin eleifend diam eget ante blandit, at semper urna euismod. Vivamus rhoncus arcu in massa condimentum, cursus congue eros ultricies. </p>
        
        <p class="newsdetail">
        <img src="images/Jellyfish.jpg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis odio. Duis at laoreet ipsum. In vitae lacinia massa. Phasellus rutrum, erat ac tempor malesuada, enim tortor malesuada velit, eu euismod augue eros ut nisi. Vivamus interdum bibendum congue. Integer semper pulvinar lectus, at vehicula ante scelerisque sed. Cras tristique felis sit amet orci ultrices mattis. Nulla quis eleifend sem, vitae rutrum nunc. Praesent quis molestie mi. Donec suscipit suscipit nisi ac suscipit. Suspendisse ante magna, accumsan a placerat non, accumsan vitae eros. Proin in turpis nec nisi imperdiet feugiat. Ut sagittis fermentum dolor, at volutpat orci tincidunt sed. Sed consectetur pharetra arcu ut sodales. Proin eleifend diam eget ante blandit, at semper urna euismod. Vivamus rhoncus arcu in massa condimentum, cursus congue eros ultricies. </p>
        
        <p class="newsdetail">
        <img src="images/Hydrangeas.jpg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed turpis odio. Duis at laoreet ipsum. In vitae lacinia massa. Phasellus rutrum, erat ac tempor malesuada, enim tortor malesuada velit, eu euismod augue eros ut nisi. Vivamus interdum bibendum congue. Integer semper pulvinar lectus, at vehicula ante scelerisque sed. Cras tristique felis sit amet orci ultrices mattis. Nulla quis eleifend sem, vitae rutrum nunc. Praesent quis molestie mi. Donec suscipit suscipit nisi ac suscipit. Suspendisse ante magna, accumsan a placerat non, accumsan vitae eros. Proin in turpis nec nisi imperdiet feugiat. Ut sagittis fermentum dolor, at volutpat orci tincidunt sed. Sed consectetur pharetra arcu ut sodales. Proin eleifend diam eget ante blandit, at semper urna euismod. Vivamus rhoncus arcu in massa condimentum, cursus congue eros ultricies. </p>